<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-interpretability-analysis" class="level1">
<h1>Regression Interpretability Analysis</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>I investigated the dangers of trusting linear regression models when relationships are non-linear. I analyzed a scenario where researchers study the relationship between social media use and anxiety, controlling for stress levels. The true relationship is known: <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, where Stress is measured by blood tests and Time represents minutes on social media.</p>
<p>However, in practice, researchers often use survey-based proxies (StressSurvey) instead of expensive blood tests. I found that even seemingly good proxy variables can lead to completely misleading regression results when the relationship between the proxy and the true variable is non-linear.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>The data shows that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> holds perfectly. The StressSurvey column represents survey-based measurements that serve as a proxy for actual stress levels measured by blood tests.</p>
</section>
<section id="question-1-bivariate-regression-analysis-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-1-bivariate-regression-analysis-with-stresssurvey">Question 1: Bivariate Regression Analysis with StressSurvey</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="b3d7a64f" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression: Anxiety ~ StressSurvey
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        23:02:01   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================

Estimated Intercept: -1.5240
Estimated StressSurvey Coefficient: 1.0470
R-squared: 0.9011

Note: True relationship is Anxiety = Stress + 0.1*Time
      StressSurvey is a proxy for Stress, not the true Stress variable</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The regression estimates a StressSurvey coefficient of 1.0470 with R² = 0.9011. This suggests a strong relationship: each one-unit increase in survey-reported stress corresponds to a 1.047-unit increase in anxiety.</p>
<p>However, this result is misleading. The true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, where Stress is measured by blood tests. StressSurvey is a non-linear proxy for true Stress—at low levels it underreports, at high levels it overreports. The coefficient of 1.0470 reflects how anxiety changes with survey responses, not with actual stress levels.</p>
<p>The high R² is deceptive: it shows a strong correlation but doesn’t guarantee interpretable coefficients. A model can fit well while telling the wrong story.</p>
</section>
<section id="question-2-visualization-of-bivariate-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-2-visualization-of-bivariate-relationship">Question 2: Visualization of Bivariate Relationship</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</p>
<div id="cell-fig-stress-survey-bivariate" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-stress-survey-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-survey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-survey-bivariate-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-survey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Bivariate relationship between StressSurvey and Anxiety with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The plot shows a strong linear relationship with R² = 0.9011. Higher StressSurvey scores clearly correspond to higher Anxiety levels, and the regression line fits the data well.</p>
<p>However, this visual fit is misleading. The points cluster at discrete StressSurvey values rather than forming a smooth distribution, revealing that StressSurvey is not measured on a continuous linear scale. The model assumes linearity, but the underlying relationship between StressSurvey and true Stress is non-linear. The regression line looks convincing, but it doesn’t capture how Anxiety actually relates to stress—only how it relates to survey responses.</p>
</section>
<section id="question-3-bivariate-regression-analysis-with-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-bivariate-regression-analysis-with-time">Question 3: Bivariate Regression Analysis with Time</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="439c51a3" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression: Anxiety ~ Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Wed, 12 Nov 2025   Prob (F-statistic):            0.00127
Time:                        23:02:02   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================

Estimated Intercept: -3.6801
Estimated Time Coefficient: 5.3406
R-squared: 0.5630

True Time Coefficient: 0.1
Difference from true: 5.2406</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The regression estimates a Time coefficient of 5.3406 with R² = 0.5630. However, the true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, where the Time coefficient should be 0.1.</p>
<p>The estimate is inflated by a factor of 53 because Stress is omitted from the model. Since Stress increases across the dataset, the regression mistakenly attributes Stress’s effect to Time. This is classic omitted variable bias: the Time coefficient absorbs the missing Stress effect, making it appear far larger than it actually is.</p>
<p>Even with statistical significance, this coefficient doesn’t represent the true effect of Time on Anxiety. Bivariate regressions can be misleading when important variables are omitted.</p>
</section>
<section id="question-4-visualization-of-bivariate-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-4-visualization-of-bivariate-relationship">Question 4: Visualization of Bivariate Relationship</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</p>
<div id="cell-fig-time-bivariate" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-time-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-bivariate-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Bivariate relationship between Time and Anxiety with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The plot shows an upward trend with R² = 0.5630. As Time increases, Anxiety increases, but the points are widely scattered around the regression line.</p>
<p>This scatter reveals the problem: Time alone doesn’t explain Anxiety well because Stress is omitted. Since Stress and Time both increase across the dataset, the regression mistakenly attributes Stress’s effect to Time, distorting the fitted line and inflating Time’s apparent impact. The visual fit looks reasonable, but it captures a confounded relationship rather than Time’s true effect.</p>
</section>
<section id="question-5-multiple-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="question-5-multiple-regression-analysis">Question 5: Multiple Regression Analysis</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both StressSurvey and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="11ed58f4" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression: Anxiety ~ StressSurvey + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        23:02:02   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================

Estimated Intercept: 0.5888
Estimated StressSurvey Coefficient: 1.4269
Estimated Time Coefficient: -2.7799
R-squared: 0.9350

True Coefficients:
  Intercept: 0
  Stress Coefficient: 1
  Time Coefficient: 0.1

Comparison:
  StressSurvey coef vs true Stress coef: 1.4269 vs 1
  Time coef vs true Time coef: -2.7799 vs 0.1</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The regression estimates a StressSurvey coefficient of 1.4269 and a Time coefficient of –2.7799, with R² = 0.9350. This suggests a strong statistical fit.</p>
<p>However, the true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, where the Stress coefficient should be 1.0 and the Time coefficient should be 0.1. The estimates are wrong in two critical ways:</p>
<p>First, the StressSurvey coefficient (1.4269) exceeds the true Stress effect (1.0) because StressSurvey is a non-linear proxy that doesn’t scale linearly with true Stress.</p>
<p>Second, and more alarming, the Time coefficient flips sign: estimated at –2.7799 when the true effect is +0.1. This happens because StressSurvey absorbs variation in Anxiety in a distorted way, leaving Time to capture whatever residual remains—even if that means producing the wrong sign.</p>
<p>This is the core problem: even with high R² and statistically significant coefficients, the model produces completely wrong conclusions. The non-linear proxy distorts the coefficients so severely that Time appears harmful when it’s actually beneficial, and the true relationship is hidden entirely.</p>
</section>
<section id="question-6-multiple-regression-analysis-with-true-stress" class="level2">
<h2 class="anchored" data-anchor-id="question-6-multiple-regression-analysis-with-true-stress">Question 6: Multiple Regression Analysis with True Stress</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both Stress and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="bc34aa8f" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression: Anxiety ~ Stress + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.600e+31
Date:                Wed, 12 Nov 2025   Prob (F-statistic):          1.15e-187
Time:                        23:02:03   Log-Likelihood:                 493.62
No. Observations:                  15   AIC:                            -981.2
Df Residuals:                      12   BIC:                            -979.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.11e-16   1.02e-15      0.109      0.915   -2.11e-15    2.34e-15
Stress         1.0000   1.15e-16   8.67e+15      0.000       1.000       1.000
Time           0.1000   8.12e-16   1.23e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        3.041   Durbin-Watson:                   0.639
Prob(Omnibus):                  0.219   Jarque-Bera (JB):                1.362
Skew:                           0.357   Prob(JB):                        0.506
Kurtosis:                       1.709   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================

Estimated Intercept: 0.0000
Estimated Stress Coefficient: 1.0000
Estimated Time Coefficient: 0.1000
R-squared: 1.0000

True Coefficients:
  Intercept: 0
  Stress Coefficient: 1
  Time Coefficient: 0.1

Comparison:
  Stress coef vs true: 1.0000 vs 1 (difference: 0.000000)
  Time coef vs true: 0.1000 vs 0.1 (difference: 0.000000)</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>Using the true Stress variable instead of StressSurvey, the regression recovers the actual relationship perfectly: Stress coefficient = 1.0000, Time coefficient = 0.1000, R² = 1.0000. These match the true formula <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> exactly.</p>
<p>This demonstrates a crucial distinction: regression works correctly when variables are properly measured. The model with StressSurvey produced inflated coefficients, a negative Time effect, and misleading interpretations. But with the true Stress variable, all those problems disappear.</p>
<p>The failures in earlier regressions were caused by bad measurement and non-linearity, not by regression itself. When relationships are truly linear and variables are measured correctly, regression performs exactly as intended.</p>
</section>
<section id="question-7-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-7-model-comparison">Question 7: Model Comparison</h2>
<p><strong>Question:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</p>
<div id="4d70852c" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Model Comparison
================================================================================
                        Model  R-squared    Intercept  Stress/StressSurvey Coef  Time Coef  Stress/StressSurvey p-value  Time p-value
Anxiety ~ StressSurvey + Time   0.935005 5.887578e-01                  1.426926  -2.779944                 2.615836e-06  2.781595e-02
      Anxiety ~ Stress + Time   1.000000 1.110223e-16                  1.000000   0.100000                3.737032e-186 5.563718e-164

================================================================================

Statistical Significance (p &lt; 0.05):

Model 1 (StressSurvey + Time):
  StressSurvey: p = 2.62e-06 ✓ Significant
  Time: p = 2.78e-02 ✓ Significant

Model 2 (Stress + Time):
  Stress: p = 3.74e-186 ✓ Significant
  Time: p = 5.56e-164 ✓ Significant</code></pre>
</div>
</div>
<div id="cell-fig-model-comparison" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-model-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-model-comparison-output-1.png" width="758" height="949" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Visual comparison of coefficient estimates from both models
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>Both models show high R² and statistically significant coefficients, yet they produce dramatically different results.</p>
<p><strong>Model 1 (StressSurvey + Time):</strong> R² = 0.935, StressSurvey coefficient = 1.4269 (inflated), Time coefficient = –2.7799 (wrong sign). Both coefficients are significant.</p>
<p><strong>Model 2 (Stress + Time):</strong> R² = 1.000, Stress coefficient = 1.0000, Time coefficient = 0.1000. Both coefficients are significant and match the true values exactly.</p>
<p>Model 1 looks statistically strong but produces completely wrong coefficients. StressSurvey overestimates the stress effect, and Time flips from a true positive effect (+0.1) to a strong negative effect (–2.78). This happens because StressSurvey is a non-linear proxy—the model forces linearity and distorts both coefficients.</p>
<p>Model 2, using the true Stress variable, recovers the exact relationship with no distortion.</p>
<p>This comparison reveals a critical lesson: a model can look statistically strong with high R² and significant p-values, yet still give completely wrong conclusions when variables are measured poorly or relationships are non-linear. Statistical significance alone does not guarantee that the model is telling the truth.</p>
</section>
<section id="question-8-real-world-implications" class="level2">
<h2 class="anchored" data-anchor-id="question-8-real-world-implications">Question 8: Real-World Implications</h2>
<p><strong>Question:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</p>
<p><strong>Answer:</strong></p>
<p>If published and reported in the news, these models would produce opposite headlines.</p>
<p><strong>Model 1 (StressSurvey + Time):</strong> With a negative Time coefficient (–2.78), the headline would likely be <em>“New Study Shows More Time on Social Media Lowers Anxiety Levels.”</em> Because StressSurvey is a poor proxy, the model misrepresents the real effect.</p>
<p><strong>Model 2 (Stress + Time):</strong> This model correctly finds that stress increases anxiety and time increases anxiety slightly (+0.1). The headline would likely be <em>“Study Finds Social Media Time Raises Anxiety, Even After Accounting for Stress.”</em></p>
<p>Parents would likely believe the second headline because it matches their intuition and experience. Social media platforms would prefer the first headline because it shifts blame away from their products.</p>
<p>These two models tell completely different stories despite both being statistically significant. The difference comes entirely from using a bad measurement (StressSurvey) instead of the true Stress variable. This demonstrates how regression can produce convincing but contradictory claims depending on how variables are measured—a real danger when findings spread to the public.</p>
</section>
<section id="question-9-avoiding-misleading-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="question-9-avoiding-misleading-statistical-significance">Question 9: Avoiding Misleading Statistical Significance</h2>
<p><strong>Question:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</p>
<div id="55cf2209" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stderr">
<pre><code>c:\mrbabu-quarto-portfolio\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-12-output-2.png" width="758" height="949" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Analyzing different subsets of the data...
================================================================================</code></pre>
</div>
</div>
<div id="658c29ef" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Subset chosen: StressSurvey &lt;= 6
Number of observations in subset: 9
Number of observations in full dataset: 15

Subset data:
   Stress  StressSurvey  Time  Anxiety
0       0             0   0.0      0.0
1       0             0   1.0      0.1
2       0             0   1.0      0.1
3       1             3   1.0      1.1
4       1             3   1.0      1.1
5       1             3   1.0      1.1
6       2             6   2.0      2.2
7       2             6   2.0      2.2
8       2             6   2.0      2.2</code></pre>
</div>
</div>
<div id="b041c362" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>
Multiple Regression on Subset: Anxiety ~ StressSurvey + Time (StressSurvey &lt;= 6)
================================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.366e+30
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           1.75e-91
Time:                        23:02:05   Log-Likelihood:                 301.93
No. Observations:                   9   AIC:                            -597.9
Df Residuals:                       6   BIC:                            -597.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         2.887e-16   6.31e-16      0.458      0.663   -1.26e-15    1.83e-15
StressSurvey     0.3333   2.17e-16   1.53e+15      0.000       0.333       0.333
Time             0.1000   8.46e-16   1.18e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        7.901   Durbin-Watson:                   0.278
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                2.800
Skew:                          -1.261   Prob(JB):                        0.247
Kurtosis:                       4.051   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

================================================================================

Estimated Intercept: 0.0000
Estimated StressSurvey Coefficient: 0.3333
Estimated Time Coefficient: 0.1000
R-squared: 1.0000

True Coefficients:
  Intercept: 0
  Stress Coefficient: 1
  Time Coefficient: 0.1

Comparison:
  StressSurvey coef vs true Stress coef: 0.3333 vs 1 (difference: 0.6667)
  Time coef vs true Time coef: 0.1000 vs 0.1 (difference: 0.0000)

Statistical Significance:
  StressSurvey: p = 0.0000 ✓ Significant
  Time: p = 0.0000 ✓ Significant</code></pre>
</div>
</div>
<div id="cell-fig-subset-analysis" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-subset-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-subset-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-subset-analysis-output-1.png" width="758" height="949" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-subset-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Comparison of coefficient estimates: full model vs subset model
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>To avoid being misled, I identified a subset where the relationship between StressSurvey and true Stress is more linear. The largest distortions occur at high StressSurvey values (8 and 12), where the survey jumps in big steps.</p>
<p>I chose all observations where StressSurvey ≤ 6, which includes lower categories (0, 3, and 6) where StressSurvey increases in small, consistent increments. This removes the non-linear jumps and makes a linear model more appropriate.</p>
<p>The subset regression (Anxiety ~ StressSurvey + Time) gives: Intercept = 0.0000, StressSurvey coefficient = 0.3333, Time coefficient = 0.1000, R² = 1.000. Both coefficients are highly significant (p &lt; 0.001).</p>
<p>The Time coefficient matches the true value exactly (0.1). The StressSurvey coefficient (0.3333) is lower than the true Stress effect (1.0), but this makes sense: in this subset, StressSurvey rises by 3 units for each 1-unit increase in Stress, so one StressSurvey unit corresponds to one-third of a Stress unit.</p>
<p>By using only the more linear region of the data, the model produces a correct positive effect of Time, avoids the earlier sign flips and coefficient distortions, and gives results that match the true relationship much more closely. This demonstrates why visual diagnostics and thoughtful subsetting are essential—and why blindly trusting full-sample regressions can lead to misleading conclusions.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Linear regression can produce high R-squared values, tiny p-values, and statistically significant coefficients—even when the model tells the wrong story. The danger isn’t the math; it’s misunderstanding what the coefficients actually represent.</p>
<p>In this analysis, StressSurvey is a distorted, non-linear proxy for true Stress. The uneven spacing between values (0, 3, 6, 9, 12) makes the scale meaningless. When the model estimates a StressSurvey coefficient of 1.43 and a Time coefficient of –2.78, these numbers don’t describe real-world effects—they describe the shape of a broken measurement tool. Even with strong statistical significance, these coefficients don’t represent how Anxiety actually responds to stress or time.</p>
<p>The most alarming failure is the sign flip: the true effect of Time is positive (+0.1), but the model estimates a strong negative effect (–2.78). This happens because when a predictor is non-linear, unevenly spaced, or measured with error, the regression tries to correct the misfit by shifting effects into other variables. StressSurvey absorbs the wrong patterns, and Time picks up the leftover distortion. The result is a model that’s statistically significant but scientifically false.</p>
<p>This has real-world consequences. A model using StressSurvey would produce the headline “More time on social media lowers anxiety,” while a model using true Stress would produce “Social media use increases anxiety, even after accounting for stress.” Both claims would be statistically significant, but only one is true. This gap between statistical significance and scientific truth is where public misunderstanding and bad policy emerge.</p>
<p>To avoid these mistakes, analysts must check for non-linearity visually, break data into meaningful subsets where linearity holds better, interpret coefficients cautiously rather than automatically, suspect sign flips as indicators of model misspecification, and measure key variables as directly as possible. The subset with StressSurvey ≤ 6 produced coefficients much closer to the true model, demonstrating the value of thoughtful subsetting.</p>
<p>Linear regression is powerful but dangerously easy to misinterpret. Even significant results can be completely wrong when variables are non-linear, mismeasured, or poorly scaled. The solution isn’t more statistics—it’s better thinking, better pictures, and better measurement.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>